export const SEARCH_SNUS_INPUT = "SEARCH_SNUS_INPUT";
export const CHANGE_CHECKED_LIST = "CHANGE_CHECKED_LIST";
export const SET_INDETERMINATE = "SET_INDETERMINATE";
export const SET_CHECK_ALL = "SET_CHECK_ALL";
export const SET_SELECTED_PRICE_SLIDER = "SET_SELECTED_PRICE_SLIDER";
export const SET_SORT_PRICE_SELECT = "SET_SORT_PRICE_SELECT";
export const SET_SHOW_BASKET = "SET_SHOW_BASKET";