export const SEARCH_SNUS_INPUT = "SEARCH_SNUS_INPUT";
export const CHANGE_CHECKED_LIST = "CHANGE_CHECKED_LIST";
export const SET_INDETERMINATE = "SET_INDETERMINATE";
export const SET_CHECK_ALL = "SET_CHECK_ALL;"